from setuptools import setup, find_namespace_packages

install_requires = ["pillow", "tornado", "numpy"]
tests_require = ["pytest", "pytest-cov", "pytest-flake8"]
dev_requires = install_requires + tests_require + ["documenteer[pipelines]"]
scm_version_template = """# Generated by setuptools_scm
__all__ = ["__version__"]

__version__ = "{version}"
"""

setup(
    name="ts_GenericCamera",
    description="CSC for Generic Camera.",
    use_scm_version={"write_to": "python/lsst/ts/GenericCamera/version.py",
                     "write_to_template": scm_version_template},
    setup_requires=["setuptools_scm"],
    install_requires=install_requires,
    package_dir={"": "python"},
    packages=find_namespace_packages(where="python"),
    package_data={"": ["*.rst", "*.yaml"]},
    scripts=["bin.src/run_genericcamera.py", "bin.src/run_liveviewui.py"],
    tests_require=tests_require,
    extras_require={"dev": dev_requires},
    license="GPL"
)
