{% set data= load_setup_py_data() %}

package:
  name: ts-genericcamera
  version: {{ data.get('version') }}

source:
  path: ../

build:
  noarch: generic
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .
  entry_points:
    - run_genericcamera = lsst.ts.genericcamera.genericcameracsc:run_genericcamera
    - run_liveviewui = lsst.ts.genericcamera.liveview.liveviewui:run_liveviewui

test:
  requires:
    - ts-conda-build =0.4
    - ts-salobj {{ salobj_version }}
    - requests
    - numpy
    - astropy
    - pillow
  source_files:
    - bin
    - pyproject.toml
    - python
    - tests
  commands:
    - pytest -v

requirements:
  host:
    - python {{ python }}
    - pip
    - setuptools_scm
    - setuptools
    - pytest-runner
  run:
    - python {{ python }}
    - setuptools
    - setuptools_scm
    - ts-idl
    - ts-salobj
    - requests
    - numpy
    - astropy
    - pillow
