# This file is part of ts_genericcamera.
#
# Developed for the Vera C. Rubin Observatory Telescope and Site Systems.
# This product includes software developed by the LSST Project
# (https://www.lsst.org).
# See the COPYRIGHT file at the top-level directory of this distribution
# for details of code ownership.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

[project]
title = "Generic Camera"
copyright = "Copyright 2018-2026 Association of Universities for Research in Astronomy"

[project.python]
package = "ts_genericcamera"
documentation_url_key = "documentation"
github_url_key = "repository"

[sphinx]
extensions = ["sphinx-jsonschema"]

[sphinx.intersphinx.projects]
ts-xml = "https://ts-xml.lsst.io"
salobj = "https://ts-salobj.lsst.io"
python = "https://docs.python.org/3.13/"
