# -------- This file is automatically generated by LSST's sconsUtils -------- #
__version__ = 'db912d3'
__repo_version__ = 'db912d3'
__fingerprint__ = 'db912d312a271a19cb479a32104c3091dd02d7e6'
__dependency_versions__ = {
}
__all__ = (
    '__version__',
    '__repo_version__',
    '__fingerprint__',
    '__dependency_versions__',
)
